name: Trigger auto deployment for mobile-spring-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'Mobile_API/**'    # Changes within the Spring Boot app folder
    - 'Dockerfile' 
    - '.github/workflows/mobile-spring-api-AutoDeployTrigger-9e6ad659-2e1e-470b-b851-52f6ffa4aca9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MOBILESPRINGAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MOBILESPRINGAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MOBILESPRINGAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile   
          registryUsername: ${{ secrets.MOBILESPRINGAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MOBILESPRINGAPI_REGISTRY_PASSWORD }}
          containerAppName: mobile-spring-api
          resourceGroup: MobileApp
          imageToBuild: mobile-spring-api:${{ github.sha }}


